//  GithubRepoAPIRouter.swift
//  CleanArchitecture-MVVM-C-RxSwift
//
//  Created by Huy Trinh Duc on 28/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import UIKit
import Alamofire

enum GithubRepoAPIRouter: APIInputBase {
    
    var headers: HTTPHeaders? {
        if requireToken {
            var header = HTTPHeaders()
            header.add(.authorization(UserUtils.getAccessToken()))
            return header
        }
        else {
            return nil
        }
    }
    
    var url: URL {
        let baseURL = URL.init(string: "https://api.github.com/search/repositories")!
        return baseURL
    }
    
    var method: HTTPMethod {
        switch self {
        case .searchRepos:
            return .get
        }
    }
    
    var encoding: ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .searchRepos(let param):
            return param
        }
    }
    
    var path: String {
        switch self {
        case .searchRepos:
            return ""
        }
    }
    
    var requireToken: Bool {
        switch self {
        case .searchRepos:
            return false
        }
    }
    
    case searchRepos(param: [String: Any])
}
