//  GithubRepoCoordinator.swift
//  CleanArchitecture-MVVM-C-RxSwift
//
//  Created by Huy Trinh Duc on 28/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import XCoordinator
import UIKit
import BaseCore
import Factory

enum GithubRepoRoute: Route {
    case main
    case test(repoName: String)
}

class GithubRepoCoordinator: NavigationCoordinator<GithubRepoRoute> {
    
    //Init bình thường
    init() {
        super.init(initialRoute: .main)
    }

    override func prepareTransition(for route: GithubRepoRoute) -> NavigationTransition {
        switch route {
        case .main:
            Container.shared.githubCoordinator.register {
                self.unownedRouter
            }
            let vc = GithubRepoViewController()
            let vm = GithubRepoViewModel()
            vc.bind(to: vm)
            return .push(vc)
        case .test(let repoName):
            let vc = PresentationTestViewController()
            let vm = PresentationTestViewModel()
            vm.repoName = repoName
            vc.bind(to: vm)
            return .push(vc)
        }
    }
    
}
