//  GithubRepoViewModel.swift
//  CleanArchitecture-MVVM-C-RxSwift
//
//  Created by Huy Trinh Duc on 28/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import RxSwift
import RxCocoa
import XCoordinator
import UIKit
import BaseCore
import Factory

class GithubRepoViewModel: EducaViewModel {
    
    struct Input {
        let triggerSearch: Driver<String>
    }
    
    struct Output {
        let repos: Driver<[GithubRepo]>
    }
    
    @Injected(\.gitHubRepoUseCase) private var useCase
    private let router: UnownedRouter<GithubRepoRoute>
    
    init(router: UnownedRouter<GithubRepoRoute>) {
        self.router = router
    }
    
    func transform(input: Input) -> Output {
        
        let repos = input.triggerSearch
            .skip(1) //skip first time
            .distinctUntilChanged()
            .debounce(.milliseconds(700))
            .flatMap { query in
                return self.useCase
                    .searchRepo(query: query)
                    .asDriverOnErrorJustComplete()
            }
        
        return Output(repos: repos)
    }
}
