//  GithubRepoViewController.swift
//  CleanArchitecture-MVVM-C-RxSwift
//
//  Created by Huy Trinh Duc on 28/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import UIKit
import RxSwift
import RxCocoa
import BaseCore

class GithubRepoViewController: EducaViewController<GithubRepoViewModel> {
    
    @IBOutlet weak var tableView: UITableView!
    
    private let bag = DisposeBag()
    private let searchController = UISearchController(searchResultsController: nil)

    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    deinit {
//        Common.log("GithubRepoViewController deinit ✅")
    }
    
    private func setupUI() {
        definesPresentationContext = true
        tableView.tableHeaderView = searchController.searchBar
        tableView.registerCell(type: GithubRepoTableViewCell.self)
    }
    
    override func bindViewModel() {
        let input = GithubRepoViewModel.Input(triggerSearch: searchController.searchBar.rx.text.orEmpty.asDriver())
        let output = viewModel.transform(input: input)
        
        output.repos
            .drive(tableView.rx.items) { tableView, index, element in
                let cell = tableView.dequeueReusableCell(type: GithubRepoTableViewCell.self, forIndexPath: IndexPath(index: index))
                cell.textLabel?.text = element.name
                return cell
            }
            .disposed(by: bag)
    }
}
