//  PresentationTestViewModel.swift
//  CleanArchitecture-MVVM-C-RxSwift
//
//  Created by Huy Trinh Duc on 28/01/2023.
//  Copyright (c) 2023 Educa Corp. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by huyparody - huytd@educa.vn

import Foundation
import RxSwift
import RxCocoa
import XCoordinator
import UIKit
import BaseCore

class PresentationTestViewModel: EducaViewModel {
    
    struct Input {
        
    }
    
    struct Output {
        let title: Driver<String>
    }

    var repoName: String = ""
    
    func transform(input: Input) -> Output {
        
        let title = Driver.just(repoName)
        
        return Output(title: title)
    }
}
